### ISSUE TITLE
retrieveConfigMapNames panic EKS 1.28

### ISSUE THREAD

**Issue by northys** [yonahd/kor#128]
**Describe the bug**
retrieveConfigMapNames results in panic

**To Reproduce**
upgraded to EKS 1.28, tried to reinstall the helm to ensure i have latest image

**Expected behavior**
no panic

**OS version, architecture and kor version**
Arch: amd64
Kor version: v0.2.7 (I hope, would be great to print version during startup)

**Additional context**
```
Server listening on :8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15ec483]

goroutine 12 [running]:
github.com/yonahd/kor/pkg/kor.retrieveConfigMapNames({0x1c37550?, 0xc00034d040?}, {0xc000392340, 0x10}, 0x0)
        /build/pkg/kor/confimgmaps.go:95 +0x1a3
github.com/yonahd/kor/pkg/kor.processNamespaceCM({0x1c37550, 0xc00034d040}, {0xc000392340, 0x10}, 0x0?)
        /build/pkg/kor/confimgmaps.go:126 +0x25f
github.com/yonahd/kor/pkg/kor.getUnusedCMs({0x1c37550?, 0xc00034d040?}, {0xc000392340, 0x10}, 0x1c37550?)
        /build/pkg/kor/all.go:23 +0x5d
github.com/yonahd/kor/pkg/kor.GetUnusedAll({{0x0?, 0x0?}, {0x0?, 0x0?}}, 0x0?, {0x1c37550, 0xc00034d040}, {0x19c3d21, 0x4}, {0x0, ...})
        /build/pkg/kor/all.go:129 +0x12d
github.com/yonahd/kor/pkg/kor.exportMetrics({{0x0?, 0xc000390540?}, {0x0?, 0xc0000607d0?}}, {0x1c37550, 0xc00034d040}, {0x19c3d21, 0x4}, {0x0, 0x0, ...})
        /build/pkg/kor/exporter.go:52 +0x185
created by github.com/yonahd/kor/pkg/kor.Exporter
        /build/pkg/kor/exporter.go:34 +0x235
```

**Comment by yonahd** [comment]
Thanks for opening the bug.
Missed this in a Code review.
I'll create a new release with this

**Comment by yonahd** [comment]
I'll open a ticket to print the version on startup as well

**Comment by northys** [comment]
It works now, thank you!
